openapi: 3.0.0
info:
  title: License Zero Vendor API
  version: 0.0.0
paths:

  /key:
    get:
      summary: Returns the public signing key of the server.
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: https://schemas.licensezero.com/1.0.0/key.json

  /offers/{offerID}:
    get:
      summary: Returns information about a license offer.
      parameters:
        - name: offerID
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          content:
            application/json:
              $ref: https://schemas.licensezero.com/1.0.0/offer.json
        400:
          description: The specified UUID is not a valid UUID.
        404:
          description: An offer with the specified UUID was not found.
        default:
          description: Unexpected Error

  /licensors/{licensorID}:
    get:
      summary: Returns information about a licensor.
      parameters:
        - name: licensorID
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: https://schemas.licensezero.com/1.0.0/licensor.json
        400:
          description: The specified UUID is not a valid UUID.
        404:
          description: An offer with the specified UUID was not found.
        default:
          description: Unexpected Error

  /order/:
    post:
      summary: Initiate an order for one or more paiod licenses.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: https://schemas.licensezero.com/1.0.0/order.json
    responses:
      303:
        description: The order is ready to complete.
        headers:
          Location:
            description: The URL for the page to complete the order.
            schema:
              type: string
              format: uri
      5XX:
        description: Unexpected Error

  receipts/{receiptID}:
    get:
      summary: Returns a receipt.
      parameters:
        - name: receiptID
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: https://schemas.licensezero.com/receipt.json
        400:
          description: The specified id is not a valid UUID.
        404:
          description: An offer with the specified UUID was not found.
        default:
          description: Unexpected Error

  bundles/{bundleID}:
    get:
      summary: Returns a bundle of receipts.
      parameters:
        - name: bundleID
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: https://schemas.licensezero.com/bundle.json
        400:
          description: The specified id is not a valid UUID.
        404:
          description: An offer with the specified UUID was not found.
        default:
          description: Unexpected Error

  orders/{orderID}:
    get:
      summary: Returns the receipts for an order.
      parameters:
        - name: orderID
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: https://schemas.licensezero.com/receipt.json
        default:
          description: Unexpected Error

  orders/{orderID}/latest:
    get:
      summary: Returns the latest receipt for an order.
      parameters:
        - name: orderID
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        302:
          headers:
            Location:
              description: The URL of the receipt.
              schema:
                type: string
                format: uri
        default:
          description: Unexpected Error
